export const programCatalogSeed = [
  {
    id: "cna",
    title: "Certified Nurse Assistant",
    summary:
      "Accelerated classroom and lab training with supervised clinical rotations built for direct patient-care roles.",
    duration: "4-6 weeks",
    schedule: "Weekday, evening, and weekend cohorts",
  },
];

export const cohortCatalogSeed = [
  {
    id: "cna-weekday-apr-2026",
    programId: "cna",
    title: "Weekday Cohort",
    startDate: "2026-04-20",
    endDate: "2026-05-18",
    scheduleLabel: "Weekday",
    meetingPattern: "Monday to Friday | 7:00 AM to 3:30 PM",
    tuitionCents: 200000,
    allowPaymentPlan: true,
    paymentPlanDepositCents: 25000,
    capacity: 15,
    isActive: true,
    sortOrder: 10,
  },
  {
    id: "cna-weekend-apr-2026",
    programId: "cna",
    title: "Weekend Cohort",
    startDate: "2026-04-25",
    endDate: "2026-06-28",
    scheduleLabel: "Weekend",
    meetingPattern: "Saturday and Sunday | 7:00 AM to 3:30 PM",
    tuitionCents: 200000,
    allowPaymentPlan: true,
    paymentPlanDepositCents: 25000,
    capacity: 15,
    isActive: true,
    sortOrder: 20,
  },
  {
    id: "cna-evening-may-2026",
    programId: "cna",
    title: "Evening Cohort",
    startDate: "2026-05-25",
    endDate: "2026-07-10",
    scheduleLabel: "Evening",
    meetingPattern: "Monday to Friday | 4:00 PM to 8:00 PM",
    tuitionCents: 200000,
    allowPaymentPlan: true,
    paymentPlanDepositCents: 25000,
    capacity: 15,
    isActive: true,
    sortOrder: 30,
  },
];
